---
title: "NEH recommendation models evaluation"
author: "Lucas Marcondes Pavelski"
date: "11/9/2020"
output:
  pdf_document:
    keep_tex: yes
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
library(FlowshopSolveR)
library(tidyverse)
library(tidymodels)
library(metaOpt)
knitr::opts_chunk$set(echo = TRUE)

MODEL_FOLDER <- here("data", "models")
TASK_NAME <- "NEH_recommendation"
TASK_FOLDER <- file.path(MODEL_FOLDER, TASK_NAME)

read_exp_dt <- function(param, model_name, exp_name, dt_name) {
  path <- file.path(TASK_FOLDER, param, paste0(model_name, ',', exp_name), dt_name)
  if (file.exists(path)) {
    readRDS(path)
  } else {
    NULL
  }
}
```

```{r, include=FALSE}
algorithm <- get_algorithm("NEH")
params <- algorithm@parameters$names[2:length(algorithm@parameters$names)]


model_names <- c(
  'decision_tree',
  'rand_forest'
)

exp_names <- c(
  'instance-based',
  # 'instance-based-c2',
  'instance-based-dependencies',
  'ablation'
)

all_exps <- expand.grid(
  param = params,
  model_name = model_names,
  exp_name = exp_names
)

test_perfs <- all_exps %>%
  mutate(perf = pmap(., read_exp_dt, dt_name = 'test_perf')) %>%
  # filter(!map_lgl(perf, is.null)) %>%
  unnest(perf)

train_perfs <- all_exps %>%
  mutate(perf = pmap(., read_exp_dt, dt_name = 'train_perf')) %>%
  # filter(!map_lgl(perf, is.null)) %>%
  unnest(perf)

all_perfs <- bind_rows(
  # mutate(train_perfs, set = 'train'),
  mutate(test_perfs, set = 'test')
) %>%
  mutate(
    model_name = case_when(
      model_name == 'decision_tree' ~ 'DT',
      model_name == 'rand_forest' ~ 'RF'
    )
  )


plot_metric <- function(pmetric) {
  all_perfs %>%
    filter(.metric == pmetric) %>%
    ggplot() +
    facet_wrap(~param, ncol = 3) +
    geom_col(aes(x = model_name, y = .estimate, fill = exp_name), 
             position = 'dodge') +
    coord_flip() +
    theme_bw() +
    theme(legend.position = 'bottom', axis.title = element_blank())
}
```

```{r, fig.asp=0.61, echo=FALSE}
 all_perfs %>%
    filter(.metric == 'accuracy')
    
```

```{r ml-results-accuracy, fig.asp=0.45, echo=FALSE}
# readRDS(here('data/models/NEH_recommendation/NEH.Init.NEH.Insertion/rand_forest,train-summ/tune_metrics')) %>%
#   filter(.metric == "accuracy") %>%
#   ggplot(aes(mtry, mean)) +
#   geom_line(alpha = 0.5, size = 1.5) +
#   geom_point() +
#   labs(y = "AUC")

getParamName <- function(param) {
  case_when(
    param == "NEH.Init.NEH.Ratio" ~ 'IOR',
    param == "NEH.Init.NEH.First.Priority" ~ 'IOI', 
    param == "NEH.Init.NEH.First.PriorityWeighted" ~ 'IOW', 
    param == "NEH.Init.NEH.First.PriorityOrder" ~ 'IOS', 
    param == "NEH.Init.NEH.Priority" ~ 'NOI', 
    param == "NEH.Init.NEH.PriorityOrder" ~ 'NOS', 
    param == "NEH.Init.NEH.PriorityWeighted" ~ 'NOW', 
    param == "NEH.Init.NEH.Insertion" ~ 'NTB'
  )
}


 all_perfs %>%
    filter(.metric == 'accuracy', exp_name != 'ablation') %>%
    mutate(
      exp_name = case_when(
        exp_name == 'instance-based' ~ 'No dependencies',
        exp_name == 'instance-based-dependencies' ~ 'With dependencies',
        T ~ as.character(exp_name)
      ),
      param = factor(getParamName(param), c(
        'IOR', 'IOI', 'IOW', 'IOS', 'NOI', 'NOS', 'NOW', 'NTB' 
      ))
    ) %>%
    ggplot() +
    facet_wrap(~param, ncol = 4) +
    geom_col(aes(x = paste(model_name), y = .estimate, fill = exp_name), 
             position = 'dodge') +
    coord_flip() +
    theme_bw() +
    theme(legend.position = 'bottom', axis.title = element_blank(), legend.title = element_blank())
```


```{r ml-results-f-measure, fig.asp=0.45, echo=FALSE}
 all_perfs %>%
    filter(.metric == 'f_meas', exp_name != 'ablation') %>%
    mutate(
      exp_name = case_when(
        exp_name == 'instance-based' ~ 'No dependencies',
        exp_name == 'instance-based-dependencies' ~ 'With dependencies',
        T ~ as.character(exp_name)
      ),
      param = factor(getParamName(param), c(
        'IOR', 'IOI', 'IOW', 'IOS', 'NOI', 'NOS', 'NOW', 'NTB' 
      ))
    ) %>%
    ggplot() +
    facet_wrap(~param, ncol = 4) +
    geom_col(aes(x = paste(model_name), y = .estimate, fill = exp_name), 
             position = 'dodge') +
    coord_flip() +
    theme_bw() +
    theme(legend.position = 'bottom', axis.title = element_blank(), legend.title = element_blank())
```

```{r, fig.asp=2, echo=FALSE}
plot_metric('f_meas') +
  ggtitle(NULL)
```

```{r, fig.asp=.5, echo=FALSE, warning=F}
library(rpart.plot)

for (param in params) {
  model <- read_exp_dt(
    param = param,
    model_name = 'decision_tree',
    exp_name = 'ablation',
    dt_name = 'model'
  )
  cat('\n\n## ', param, ' decision tree\n')
  if (!is.null(model)) {
    rpart.plot(model$fit$fit$fit, type = 5, extra = 0)
    
    print(rpart.rules(model$fit$fit$fit))
  }
}

```

```{r, fig.asp=1, echo=FALSE, results='asis', warning=F}
library(vip)

for (param in params) {
  model <- read_exp_dt(
    param = param,
    model_name = 'decision_tree',
    exp_name = 'instance-based',
    dt_name = 'model'
  )
  
  cat("\n\n##", param, '\n\n')
  
  model %>% 
    pull_workflow_fit() %>% 
    vip() %>%
    show()
}
```

```{r}

best_instance <- readRDS(file.path(TASK_FOLDER, 'results', 'none,instance_best.rda')) %>%
  unnest(problem) %>%
  rename(best_fitness = fitness)

# test_problems_df()

experiments <- tribble(
  ~ml_model, ~strat,
  'decision_tree', 'instance-based',
  'decision_tree', 'instance-based-dependencies',
  'rand_forest', 'instance-based',
  'rand_forest', 'instance-based-dependencies',
  # 'decision_tree', 'ablation',
  # 'rand_forest', 'ablation',
  'none', 'default',
  'none', 'global_best',
  'none', 'random',
) %>%
  mutate(results = pmap(., function(ml_model, strat) file.path(TASK_FOLDER,
                                        'results',
                                        paste0(ml_model, ',', strat, '.rda')))) %>%
  mutate(results = map(results, function(res) {
    print(res)
    readRDS(res)
  })) %>%
  unnest(results) %>%
  unnest(problem) %>%
  select(-config) %>%
  left_join(best_instance) %>%
  mutate(rp = 100 * (fitness - best_fitness) / best_fitness)



```

```{r results='asis'}
experiments %>%
  group_by(strat, ml_model) %>%
  summarize(
    q00 = quantile(rp, 0.00),
    q25 = quantile(rp, 0.25),
    q50 = quantile(rp, 0.50),
    q75 = quantile(rp, 0.75),
    q1  = quantile(rp, 1.00),
  ) # %>% knitr::kable(format = 'latex')
```


```{r strategies-comparison, fig.height=2}
library(ggallin)

experiments %>%
  mutate(model_strat = factor(
    paste(ml_model, strat),
    levels = c(
      'none default',
      'none global_best',
      'decision_tree instance-based',
      'decision_tree instance-based-dependencies',
      'rand_forest instance-based',
      'rand_forest instance-based-dependencies'
    ),
    labels = c(
      'Standard NEH',
      'Global-best NEH',
      'DT',
      'DT+Dependencies',
      'RF',
      'RF+Dependencies'
    )
  )) %>%
  ggplot() +
  geom_violin(aes(x = model_strat, fill = model_strat, y = rp)) +
  scale_y_continuous(trans = pseudolog10_trans) +
  scale_fill_viridis_d() +
  theme_bw() +
  theme(axis.title = element_blank(), axis.text.x = element_blank()) +
  labs(fill = "Strategy")
```

```{r strategies-comparison-without-random}
library(ggallin)

experiments %>%
  filter(strat != 'random') %>% # , ml_model != 'decision_tree'
  mutate(model_strat = factor(
    paste(ml_model, strat),
    levels = c(
      'none default',
      'none global_best',
      'decision_tree instance-based',
      'decision_tree instance-based-dependencies',
      'rand_forest instance-based',
      'rand_forest instance-based-dependencies'
    ),
    labels = c(
      'Standard NEH',
      'Global-best NEH',
      'DT',
      'DT+Dependencies',
      'RF',
      'RF+Dependencies'
    )
  )) %>%
  ggplot() +
  geom_violin(aes(x = model_strat, fill = model_strat, y = rp)) +
  scale_y_continuous(trans = pseudolog10_trans) +
  scale_fill_viridis_d() +
  theme_bw() +
  theme(axis.title = element_blank(), axis.text.x = element_blank()) +
  geom_segment(aes(x = 0.5, xend=2.5, y=30, yend=30)) +
  geom_segment(aes(x = 2.5, xend=5.5, y=20, yend=20)) +
  labs(fill = "Strategy")
```


```{r}
stat_data <- experiments %>%
  mutate(
    block = paste(model, instance),
    group = factor(paste(ml_model, strat),
    levels = c(
      'rand_forest instance-based-dependencies',
      'rand_forest instance-based',
      'decision_tree instance-based-dependencies',
      'decision_tree instance-based',
      'none global_best',
      'none default',
      'none random'
    )),
    y = rp
  ) %>%
  select(block, group, y) %>%
  arrange(group != 'rand_forest instance-based-dependencies')

PMCMRplus::frdManyOneDemsarTest(stat_data$y, stat_data$group, stat_data$block)
```


```{r}
stat_data <- experiments %>%
  mutate(
    block = paste(model, instance),
    group = factor(paste(ml_model, strat),
    levels = c(
      'decision_tree instance-based-dependencies',
      'rand_forest instance-based-dependencies',
      'rand_forest instance-based',
      'decision_tree instance-based',
      'none global_best',
      'none default',
      'none random'
    )),
    y = rp
  ) %>%
  select(block, group, y) %>%
  arrange(group != 'rand_forest instance-based-dependencies')

PMCMRplus::frdManyOneDemsarTest(stat_data$y, stat_data$group, stat_data$block)
```


```{r}
stat_data <- experiments %>%
  mutate(
    block = paste(model, instance),
    group = factor(paste(ml_model, strat),
    levels = c(
      'decision_tree instance-based-dependencies',
      'rand_forest instance-based-dependencies',
      'rand_forest instance-based',
      'decision_tree instance-based',
      'none global_best',
      'none default',
      'none random'
    )),
    y = rp
  ) %>%
  select(block, group, y) %>%
  arrange(group != 'rand_forest instance-based-dependencies')

PMCMRplus::frdAllPairsNemenyiTest(stat_data$y, stat_data$group, stat_data$block)
```

