---
title: "IG with adaptive operator selection for flowshop problems"
output:
  pdf_document:
    keep_tex: true
header-includes:
  \usepackage{longtable}
  \usepackage{booktabs}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      collapse = TRUE,
                      comment = "#>",
                      fig.path = "graphics/knitr-",
                      fig.retina = 2, # Control using dpi
                      fig.width = 6,  # generated images
                      fig.pos = "t",  # pdf mode
                      fig.align = "center",
                      dpi = if (knitr::is_latex_output()) 72 else 300, 
                      out.width = "100%",
                      # dev = "svg",
                      dev.args = list(png = list(type = "cairo-png")),
                      optipng = "-o1 -quiet")
library(FlowshopSolveR)
library(tidyverse)
library(here)
library(PMCMRplus)
library(wrapr)
library(mmtable2)

wrangle_perf <- function(dt) {
  dt %>%
    mutate(prob_data = map(problem, ~as_tibble(.x@data))) %>% 
    select(-problem) %>% 
    unnest(prob_data) %>%
    mutate(fitness = map_dbl(result, ~.x$cost))
}


load_perf <- function(path) {
  perfs <- read_rds(path)
  perfs %>%
    wrangle_perf()
}


problems <- read_rds(here("reports", "aos", "data", "train_test_sets_df.rds"))

train_problems <- problems %>%
  filter(set_type == "train")

test_problems <- problems %>%
  filter(set_type == "test")



load_perfs <- function(perf_folder, path = "all") {
  tibble(
    path = path,
    full_path = file.path(perf_folder, path)
  ) %>%
    select(path, full_path) %>%
    mutate(
      perfs = map(full_path, function(path) {
        tibble(
          algo = dir(path),
          perf = map(file.path(path, algo), load_perf)
        )
      })
    ) %>%
    unnest(perfs) %>%
    unnest(perf) %>%
    mutate(algo = str_replace_all(algo, "^ig|\\.rds$", "")) %>%
    group_by(path, id) %>%
    mutate(arfp = 100 * (fitness - min(fitness)) / min(fitness))
}

```

```{r load}
experiments <- c("01-adaptive_destruction_size", 
"02-adaptive_best_insertion", "03-adaptive_destruction_position", 
"04-adaptive_local_search", "05-adaptive_perturb", "06-adaptive_neighborhood_size")


perf_experiments <- c(experiments, "09-final_comparison")

perfs <- map(perf_experiments, ~{
  exp_folder <- here("reports", "aos", "data", .x)
  perf_folder <- file.path(exp_folder, "perf")
  load_perfs(perf_folder) %>%
    mutate(experiment = .x)
})

names(perfs) <- perf_experiments
```


```{r adaptive_destruction_size-plt}
perfs[["01-adaptive_destruction_size"]] %>%
  ggplot(aes(x = algo, fill = algo, y = arfp)) +
  geom_violin() + 
  labs(x = NULL) +
  scale_y_continuous(trans = "pseudo_log") +
  ggtitle("Adaptive destruction size") + 
  theme_minimal()
```


```{r}
perfs[["01-adaptive_destruction_size"]] %>%
  group_by(id) %>%
  mutate(rank = rank(fitness)) %>%
  select(algo, id, rank) %>%
  ggplot(aes(x = algo, fill = algo, y = rank)) +
  geom_violin() + 
  labs(x = NULL) +
  ggtitle("Adaptive destruction size") + 
  theme_minimal()
```


```{r}
perfs[["01-adaptive_destruction_size"]] %>%
  group_by(algo) %>%
  summarize(
    q00 = quantile(arfp, 0.0),
    q25 = quantile(arfp, 0.25),
    q50 = quantile(arfp, 0.5),
    mean = mean(arfp),
    q75 = quantile(arfp, 0.75),
    q100 = quantile(arfp, 1.00)
  ) %>% knitr::kable(booktabs = TRUE)
```


```{r}
algo_perfs <- perfs[["01-adaptive_destruction_size"]]
frdAllPairsNemenyiTest(algo_perfs$arfp, algo_perfs$algo, paste(algo_perfs$id, "-", algo_perfs$seed))
```

```{r adaptive_best_insertion-plt}
perfs[["02-adaptive_best_insertion"]] %>%
  ggplot(aes(x = algo, fill = algo, y = arfp)) +
  geom_violin() + 
  labs(x = NULL) +
  scale_y_continuous(trans = "pseudo_log") +
  ggtitle("Adaptive local search focus") + 
  theme_minimal()
```


```{r}
perfs[["02-adaptive_best_insertion"]] %>%
  group_by(algo) %>%
  summarize(
    q00 = quantile(arfp, 0.0),
    q25 = quantile(arfp, 0.25),
    q50 = quantile(arfp, 0.5),
    mean = mean(arfp),
    q75 = quantile(arfp, 0.75),
    q100 = quantile(arfp, 1.00)
  ) %>% knitr::kable(booktabs = TRUE)
```

```{r}
algo_perfs <- perfs[["02-adaptive_best_insertion"]]
frdAllPairsNemenyiTest(algo_perfs$arfp, algo_perfs$algo, paste(algo_perfs$id, "-", algo_perfs$seed))
```


```{r adaptive_destruction_position-plt}
exp_folder <- here("reports", "aos", "data", "03-adaptive_destruction_position")
perf_folder <- file.path(exp_folder, "perf")
irace_folder <- file.path(exp_folder, "irace")

algo_perfs <- load_perfs(perf_folder)

algo_perfs %>%
  ggplot(aes(x = algo, fill = algo, y = arfp)) +
  geom_violin() + 
  labs(x = NULL) +
  scale_y_continuous(trans = "pseudo_log") +
  ggtitle("Adaptive destruction position") + 
  theme_minimal()
```

```{r}
algo_perfs %>%
  group_by(algo) %>%
  summarize(
    q00 = quantile(arfp, 0.0),
    q25 = quantile(arfp, 0.25),
    q50 = quantile(arfp, 0.5),
    mean = mean(arfp),
    q75 = quantile(arfp, 0.75),
    q100 = quantile(arfp, 1.00)
  ) %>% knitr::kable(booktabs = TRUE)
```

```{r}
frdAllPairsNemenyiTest(algo_perfs$arfp, algo_perfs$algo, paste(algo_perfs$id, "-", algo_perfs$seed))
```


```{r adaptive_local_search-plt}
exp_folder <- here("reports", "aos", "data", "04-adaptive_local_search")
perf_folder <- file.path(exp_folder, "perf")
irace_folder <- file.path(exp_folder, "irace")

algo_perfs <- load_perfs(perf_folder)

algo_perfs %>%
  ggplot(aes(x = algo, fill = algo, y = arfp)) +
  geom_violin() + 
  labs(x = NULL) +
  scale_y_continuous(trans = "pseudo_log") +
  ggtitle("Adaptive local search") + 
  theme_minimal()
```

```{r}
algo_perfs %>%
  group_by(algo) %>%
  summarize(
    q00 = quantile(arfp, 0.0),
    q25 = quantile(arfp, 0.25),
    q50 = quantile(arfp, 0.5),
    mean = mean(arfp),
    q75 = quantile(arfp, 0.75),
    q100 = quantile(arfp, 1.00)
  ) %>% knitr::kable(booktabs = TRUE)
```

```{r}
frdAllPairsNemenyiTest(algo_perfs$arfp, algo_perfs$algo, paste(algo_perfs$id, "-", algo_perfs$seed))
```

```{r adaptive_perturb-plt}
exp_folder <- here("reports", "aos", "data", "05-adaptive_perturb")
perf_folder <- file.path(exp_folder, "perf")
irace_folder <- file.path(exp_folder, "irace")

algo_perfs <- load_perfs(perf_folder)

algo_perfs %>%
  ggplot(aes(x = algo, fill = algo, y = arfp)) +
  geom_violin() + 
  labs(x = NULL) +
  scale_y_continuous(trans = "pseudo_log") +
  ggtitle("Adaptive perturbation") + 
  theme_minimal()
```

```{r}
algo_perfs %>%
  group_by(algo) %>%
  summarize(
    q00 = quantile(arfp, 0.0),
    q25 = quantile(arfp, 0.25),
    q50 = quantile(arfp, 0.5),
    mean = mean(arfp),
    q75 = quantile(arfp, 0.75),
    q100 = quantile(arfp, 1.00)
  ) %>% knitr::kable(booktabs = TRUE)
```

```{r}
frdAllPairsNemenyiTest(algo_perfs$arfp, algo_perfs$algo, paste(algo_perfs$id, "-", algo_perfs$seed))
```


```{r adaptive_neighborhood_size-plt}
algo_perfs <- perfs[["06-adaptive_neighborhood_size"]]

algo_perfs %>%
  ggplot(aes(x = algo, fill = algo, y = arfp)) +
  geom_violin() + 
  labs(x = NULL) +
  scale_y_continuous(trans = "pseudo_log") +
  ggtitle("Adaptive neighborhood size") + 
  theme_minimal()
```

```{r}
algo_perfs %>%
  group_by(algo) %>%
  summarize(
    q00 = quantile(arfp, 0.0),
    q25 = quantile(arfp, 0.25),
    q50 = quantile(arfp, 0.5),
    mean = mean(arfp),
    q75 = quantile(arfp, 0.75),
    q100 = quantile(arfp, 1.00)
  ) %>% knitr::kable(booktabs = TRUE)
```

```{r}
frdAllPairsNemenyiTest(algo_perfs$arfp, algo_perfs$algo, paste(algo_perfs$id, "-", algo_perfs$seed))
```



```{r}
perfs %>%
  bind_rows() %>%
  group_by(experiment, algo) %>%
  summarise(
    arfp = sprintf("%.3f (%.3f)", mean(arfp), sd(arfp))
  ) %>%
  pivot_wider(names_from = "algo", values_from = "arfp") %>%
  knitr::kable(booktabs = TRUE)
```

```{r}
filter_ig_default <- function(config) {
  remove_param <- c(
    "IG.AdaptivePosition.AOS.WarmUp.Strategy",
    # "IG.AdaptivePosition.AOS.Options",
    "IG.AdaptivePosition.AOS.Strategy",
    "IG.AdaptiveBestInsertion.AOS.Strategy",
    "IG.AdaptivePerturb.AOS.Strategy",
    "IG.AdaptiveLocalSearch.AOS.Strategy",
    "IG.AdaptiveNeighborhoodSize.AOS.Strategy",
    "IG.AOS.Strategy"
  )
  config[(str_detect(names(config), "AOS") |
          str_detect(names(config), "AdaptiveBestInsertion") |
          str_detect(names(config), "AdaptivePosition")) &
        !(names(config) %in% remove_param)]
}

format_config <- function(config) {
  param_names <- names(config) %>%
    str_replace("PM\\.RewardType", "PMRewardType") %>%
    str_remove("^IG\\.(AdaptivePosition|AdaptiveLocalSearch|AdaptiveBestInsertion|AdaptiveNeighborhoodSize|AdaptivePerturb)\\.AOS\\.") %>%
    str_remove("^IG\\.AOS\\.") %>%
    str_remove("^IG\\.AdaptiveBestInsertion\\.") %>%
    str_remove("^IG\\.AdaptivePosition\\.") %>%
    str_remove("^(PM|FRRMAB|LINUCB|TS)\\.")
  paste(param_names, config, sep = " = ")
}

load_config <- function(config_path) {
  read_rds(config_path)[1,] %>%
    df_to_character() %>%
    filter_ig_default() %>%
    format_config()
}

load_configs <- function(irace_folder, path = "all") {
  tibble(
    path = path,
    full_path = file.path(irace_folder, path)
  ) %>%
    select(path, full_path) %>%
    mutate(
      configs = map(full_path, function(path) {
        tibble(algo = dir(path)) %>%
          filter(!str_detect(algo, "_log|_rec")) %>%
          mutate(config = map(file.path(path, algo), load_config))
      })
    ) %>%
    unnest(configs)
}

configs_tidy <- map_dfr(experiments, ~{
  here("reports", "aos", "data", .x) %>%
    file.path("irace") %>%
    load_configs() %>%
    mutate(exp = .x) %>%
    select(exp, algo, config)
}) %>%
  unnest(config) %>%
  separate(config, c("param", "value"), sep = " = ")
```


```{r}
# configs_tidy %>%
#   filter((param %in% c("RewardType"))) %>% 
#   filter(!(param %in% c("WarmUp.Strategy"))) %>%  # pivot_wider(names_from = "param", values_from = "value") %>%
#   arrange(exp, algo, param) %>%
#   mmtable(value) +
#   header_top(algo) +
#   header_left(exp)
```


```{r}
configs_tidy %>%
  filter((param %in% c("Options"))) %>% 
  filter(!(param %in% c("WarmUp.Strategy"))) %>%  # pivot_wider(names_from = "param", values_from = "value") %>%
  arrange(exp, algo, param) %>%
  mmtable(value) +
  header_top(algo) +
  header_left(exp)
```


```{r}
configs_tidy %>%
  filter((param %in% c("NoArms"))) %>% 
  filter(!(param %in% c("WarmUp.Strategy"))) %>%  # pivot_wider(names_from = "param", values_from = "value") %>%
  arrange(exp, algo, param) %>%
  mmtable(value) +
  header_top(algo) +
  header_left(exp)
```


```{r}
configs_tidy %>%
  filter((param %in% c("WindowSize", "UpdateWindow", "C"))) %>% 
  filter(!(param %in% c("WarmUp.Strategy"))) %>%  # pivot_wider(names_from = "param", values_from = "value") %>%
  arrange(exp, algo, param) %>%
  mmtable(value) +
  header_top(algo) +
  header_left(exp)
```



```{r final_comparison-plt}
algo_perfs <- perfs[["09-final_comparison"]]

algo_perfs %>%
  ggplot(aes(x = algo, fill = algo, y = arfp)) +
  geom_violin() + 
  labs(x = NULL) +
  scale_y_continuous(trans = "pseudo_log") +
  ggtitle("Adaptive perturb-ds") + 
  theme_minimal()
```


```{r}
frdAllPairsNemenyiTest(algo_perfs$arfp, algo_perfs$algo, paste(algo_perfs$id, "-", algo_perfs$seed))
```


```{r}
perfs[["09-final_comparison"]] %>%
  bind_rows() %>%
  group_by(experiment, algo) %>%
  summarise(
    arfp = sprintf("%.3f (%.3f)", mean(arfp), sd(arfp))
  ) %>%
  pivot_wider(names_from = "algo", values_from = "arfp") %>%
  knitr::kable("latex", booktabs = TRUE)
```


```{r}
frdAllPairsNemenyiTest(perfs[["09-final_comparison"]]$arfp, perfs[["09-final_comparison"]]$algo, paste(perfs[["09-final_comparison"]]$id, "-", algo_perfs$seed))
```




```{r}
perfs[["09-final_comparison"]] %>%
  bind_rows() %>%
  group_by(experiment, algo, objective) %>%
  summarise(
    arfp = sprintf("%.3f (%.3f)", mean(arfp), sd(arfp))
  ) %>%
  pivot_wider(names_from = "algo", values_from = "arfp") %>%
  knitr::kable(booktabs = TRUE)
```


```{r}
test_by_group <- function(perfs, group_var) {
  perfs %>% 
    group_by(across(group_var)) %>%
    group_split(.keep = TRUE) %>%
    map(~frdAllPairsNemenyiTest(.x$arfp, paste(.x$algo, .x[[group_var]]), paste(.x$id, "-", .x$seed)))
}

test_by_group(perfs[["09-final_comparison"]], 'objective')
```

```{r}
perfs[["09-final_comparison"]] %>%
  bind_rows() %>%
  group_by(experiment, algo, type) %>%
  summarise(
    arfp = sprintf("%.3f (%.3f)", mean(arfp), sd(arfp))
  ) %>%
  pivot_wider(names_from = "algo", values_from = "arfp") %>%
  knitr::kable("latex", booktabs = TRUE)
```

```{r}
test_by_group(perfs[["09-final_comparison"]], 'type')
```




```{r}
perfs[["09-final_comparison"]] %>%
  bind_rows() %>%
  group_by(experiment, algo, dist, corr) %>%
  summarise(
    arfp = sprintf("%.3f (%.3f)", mean(arfp), sd(arfp))
  ) %>%
  pivot_wider(names_from = "algo", values_from = "arfp") %>%
  knitr::kable("latex", booktabs = TRUE)
```

```{r}
test_by_group(perfs[["09-final_comparison"]] %>% mutate(dist_corr = paste(dist, corr)), 'dist_corr')
```



```{r}
perfs[["09-final_comparison"]] %>%
  bind_rows() %>%
  group_by(experiment, algo, no_jobs) %>%
  summarise(
    arfp = sprintf("%.3f (%.3f)", mean(arfp), sd(arfp))
  ) %>%
  pivot_wider(names_from = "algo", values_from = "arfp")
# %>%
  # knitr::kable("latex", booktabs = TRUE)
```

```{r}
test_by_group(perfs[["09-final_comparison"]], 'no_jobs')
```
