# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initFactories <- function(data_folder) {
    invisible(.Call(`_FlowshopSolveR_initFactories`, data_folder))
}

solveFSP <- function(mh, rproblem, seed, rparams, verbose = FALSE) {
    .Call(`_FlowshopSolveR_solveFSP`, mh, rproblem, seed, rparams, verbose)
}

sampleSolutionStatisticsFLA <- function(dataFolder, rproblem, noSamples, seed) {
    .Call(`_FlowshopSolveR_sampleSolutionStatisticsFLA`, dataFolder, rproblem, noSamples, seed)
}

sampleRandomWalk <- function(dataFolder, rproblem, noSamples, samplingStrat, seed) {
    .Call(`_FlowshopSolveR_sampleRandomWalk`, dataFolder, rproblem, noSamples, samplingStrat, seed)
}

adaptiveWalk <- function(rproblem, rsampling, seed) {
    .Call(`_FlowshopSolveR_adaptiveWalk`, rproblem, rsampling, seed)
}

adaptiveWalkLengthFLA <- function(rproblem, rsampling, seed) {
    .Call(`_FlowshopSolveR_adaptiveWalkLengthFLA`, rproblem, rsampling, seed)
}

enumerateAllFitness <- function(rproblem) {
    .Call(`_FlowshopSolveR_enumerateAllFitness`, rproblem)
}

enumerateSolutions <- function(fspInstance, fspProblem) {
    .Call(`_FlowshopSolveR_enumerateSolutions`, fspInstance, fspProblem)
}

sampleLON <- function(rproblem, rsampling, seed) {
    .Call(`_FlowshopSolveR_sampleLON`, rproblem, rsampling, seed)
}

